### ISSUE TITLE
add buffering icon

### ISSUE THREAD

**Issue by vtproduction** [brucetoo/VideoControllerView#1]
Thks for your work, it helped me alot learning about media controller.
Could you please write the function to display the buffering (circle progress bar, etc.) while the video is loading ?
Thank you !

**Comment by brucetoo** [comment]
Maybe this weekend i will try..But you can add Loading view as my example code does now.. [Here](https://github.com/brucetoo/VideoControllerView/blob/master/app/src/main/res/layout/activity_video_player.xml)
