### ISSUE TITLE
Needs improvements

### ISSUE THREAD

**Issue by taimur97** [brucetoo/VideoControllerView#2]
Hi,
It still needs many small improvements such as implement wake lock, handle orientation, the controller of brightness and sound is very small if I swipe a little it turns the volume to full/zero and the video screen is not full the notification bar is still displayed even when full screen mode.

**Comment by brucetoo** [comment]
please check out new code,sorry for handle this too late

**Comment by brucetoo** [comment]
i think “wake lock, handle orientation” not the work of VideoControllerView..
