### ISSUE TITLE
Not able to find VideoMediaController.MediaPlayerControl

### ISSUE THREAD

**Issue by amanarora12** [brucetoo/VideoControllerView#3]
I am not able to find VideoMediaController.MediaPlayerControl interface in either the android stack or in this repository.

**Comment by brucetoo** [comment]
VideoMediaController ? What do you mean

**Comment by amanarora12** [comment]
In the README file, in the how to use section, it says that 'Implement VideoMediaController.MediaPlayerControl'.
But i figured that it means the VideoControllerView.MediaPlayerControlListener.  
No issues now.

**Comment by brucetoo** [comment]
Hmmm....
