### ISSUE TITLE
Cannot import in android studio

### ISSUE THREAD

**Issue by premacck** [brucetoo/VideoControllerView#8]
I tried importing this library in android through `compile 'com.github.brucetoo:VideoControllerView:de3c249ec2'`, also included `maven { url 'https://jitpack.io' }` in project level build.gradle.
but it is giving me this error:

> Error:Dependency com.github.brucetoo:VideoControllerView:de3c249ec2 on project app resolves to an APK archive which is not supported as a compilation dependency. File: C:\Users\Prem $\.gradle\caches\modules-2\files-2.1\com.github.brucetoo\VideoControllerView\de3c249ec2\722364165399ae98d197f462778c245f86db3ecb\VideoControllerView-de3c249ec2.apk

**Comment by brucetoo** [comment]
why not fork source code instead of jitpack ?
